export const introduccion = [
        " Bug está compuesto por doce textos.",
        " BUG iba a ser apenas un poema pero creció demasiado, a la fuerza y sin querer.",
        " BUG fue un fanzine; hubieron solo diez copias.",
        " BUG toma imágenes de internet y las altera.",    
        " BUG toma imágenes de la vida real y las distorsiona",    
        " BUG es el resultado de la tecnología calando en la rutina y los vínculos.",
        " BUG es el resultado de la tecnología como refugio de la rutina y los vínculos.",
        " BUG anhela una naturaleza que ya no existe.",
        " BUG circula la gran ciudad sin entenderla.",    
        " BUG es la experiencia con una realidad rota, fragmentada, inasible; nada que no sepamos.",
        " BUG se fue mapeando entre Buenos Aires, La Plata y Trelew.",
        " BUG se escribió entre 2020 y 2022.",
];

export const poemas = [
        [
                ">Genius K640",
                " ",
                ">los dedos de alguien teclean un nombre",
                "y su correspondiente apellido fecha",
                "de nacimiento DNI CUIT país provincia",
                "ciudad barrio dirección postal",
                "profesión estado civil mail en minúscula",
                "arroba yahoo punto com punto ar.",
                "los ojos en la cara de ese alguien",
                "que no deja de recibir el lechazo", 
                "en seco del monitor sobrecalentado", 
                "escanean de un vistazo rápido los datos", 
                "en los casilleros. se buscan posibles", 
                "errores con el objetivo de reducir",
                "al máximo futuros coágulos que obstruyan",
                "el cauce informativo. la seguridad que", 
                "surge de la repetición repetición repetición",
                "de una tarea da por finalizado", 
                "el procedimiento.",
                "es cuando el índice en la mano derecha",
                "responde sin titubeos. presiona ENTER.",
                "la barra carga en su jeringa",
                "un líquido verde: 98% 99% 100%", 
                "y la página pasa a otra cosa.",
                "dilatada por todo lo anterior, la memoria", 
                "no retiene un gramo de información",
                "pero eso al menos por hoy, importa poco,",
                "por no decir, nada.",
        ],
        [
                ">Epifanía de una creación",
                " ",
                ">meses de planificación. cambios", 
                "en el equipo. un año tornadizo hasta", 
                "que agarró viaje. par de ojos,", 
                "brazos articulados, dos piernas",
                "que aguantan su peso neto.",
                "grita, habla, llora si el contexto", 
                "así lo requiere,",
                "se enamora de acuerdo a sus cálculos,", 
                "tiene un sueño autodidacta", 
                "que no aparece en los monitores", 
                "y contra todo pronóstico",
                "jamás le había pasado: ¿la resaca?",
                "¿la densidad de la ciudad disecada",
                "por otro verano nefasto? ¿el eco",
                "de otra noche en la discoteca suburbana",
                "latiendo todavía en sus oídos", 
                "de aluminio? tal vez va por ahí,", 
                "tal vez es como estar",
                "detrás del gran espectáculo, como fabular",
                "con un espejo de pura maldición invertida",
                "que rebota contra otro espejo.",
                "y que al replicarse al infinito,",
                "un latigazo mental que explica que",
                "lo que le duele no es la cabeza,",
                "es haber descubierto el faro",
                "que escanea 24/7 las sombras",
                "de su consciencia.",

        ],
        [
                ">00:00",
                " ",
                ">podríamos afirmar que todo éste", 
                "mal sueño empezó la vuelta esa allá", 
                "en el parque atrás de la autopista", 
                "cuando del cielo cayó una gota opaca", 
                "que te perforó la mano.", 
                "fueron tres días sin curita,", 
                "de sacarse con cuidado la pelusa",
                "adherida a la ampolla y unos quince más",
                "hasta que la superficie rosácea", 
                "recuperó la textura", 
                "y su color original: un #e3a776",
                "rebajado por la anemia, levemente",
                "satinado por los bloques de tiempo",
                "expuesto a la luz artificial.",

        ],
        [
                ">Disorder",
                " ",
                ">algo así como despertar sin alarma",
                "y dejar de escuchar el ruido del sol",
                "proyectándose sobre la materialidad",
                "de las cosas. fue, dejarla pasar.", 
                "despertar al siguiente", 
                "en la misma posición",
                "en la que estabas y mirarte rápido",
                "las palmas de las manos para constatar",
                "que todavía se está en actividad,", 
                "que todavía nadie desenchufó la línea",
                "grisácea que mantiene tensa",
                "la urdimbre de estos pensamientos.",
                "por una milésima de segundos, dudar,",
                "y por dudar, asustarse. obviamente,",
                "no contárselo a nadie.",

        ],
        [
                ">Lo postergado",
                " ",
                ">con tus propias manos dijiste pero",
                "no veo la cabaña en el medio del bosque,",
                "ni la montaña nevada detrás.", 
                "no hay árboles a la redonda,", 
                "tampoco estrellas. acá el fuego",
                "no nace de las leñas, es gas coloreado.",
                "acá el cielo todavía sigue duro.",
                " ",
                "colgado en la etiqueta", 
                "de un agua mineral,",
                "vas de lo que sos a lo que pudiste ser,",
                "de lo que sabés a lo que no sabés de vos.",
                "seguís donde siempre estuviste,",
                "conforme a la fuerza,",
                "encerrado en días que pasan",
                "aterradoramente lentos,",
                "queriendo lo que todos: una quietud",
                "finita entre tiempo y espacio, un lugar",
                "en el mundo al que nadie ha ido,",
                "un campito donde tu nombre caiga",
                "y pesada en la tierra se pudra.,"

        ],
        [
                ">Fulgente",
                " ",
                ">descubrí al núcleo crecer, fulgente",
                "agigantaba su espectro. el eclipse",
                "era total, a punto de reventar contra",
                "las paredes de la habitación.",
                "a oscuras una luz que nacía", 
                "de adentro nuestro,",
                "no importaba el mundo; el exterior",
                "era una bolsa de nylon", 
                "que un camión de basura", 
                "con sus dientes cuadrados trituraba.",
                "no importaban los amigos, las palabras",
                "reversibles, las desgracias", 
                "no tenían cabida",
                "en este improvisado escenario.",
                " ",
                "y así pasamos el feriado,", 
                "entre un frío otoñal",
                "y la inconsciencia de abrir", 
                "por unas horas",
                "la válvula ubicada detrás del nudo",
                "del incontrolable cablerío: la paz al ver",
                "que la turbiedad que traigo,",
                "lejos de tus ojos, se vierte.",

        ],
        [
                ">Dúctil",
                " ",
                ">en este sueño negro,",
                "dentro de esta masa dúctil,",
                "bajo este anillo de 220 w,",
                "por el corredor de un sanatorio",
                "reluciente en desinfectante barato,",
                "tras la correntada de aire",
                "que por las hojas de madera ingresa,",
                "hacia el aliento frío",
                "de un dóberman encadenado",
                "y el tabaco industrial que incineran",
                "a toda velocidad los enfermeros",
                "en la vereda contra el entretiempo",
                "de la muerte que espera.",

        ],
        [
                ">Doom",
                " ",
                ">insomne, constante, sin testigos.",
                "pudiste haber sido vos, en una de esas",
                "pudiste haber desarrollado una adaptación",
                "feroz al ambiente reconvertido. un ojo",
                "de más a la altura del corazón, un láser",
                "potente disparado al abrirlo, otra",
                "voz, o porqué no, la pericia emocional",
                "de quien sabe deslizarse a través",
                "de horizontes inestables. pero no, ni vos",
                "ni nadie que presencie ahora", 
                "el latir amarillo del mundo.", 
                "hipo de fotones. intermitencia",
                "que marca el ritmo de la distopía.",
                "humanos cero, nadie que absorba", 
                "los mensajes oxidándose", 
                "en los carteles cascoteados. indicios", 
                "de que supo haber movimiento, direcciones,", 
                "líneas de existencia programada",
                " ",
                "de un punto A a un punto B.",
                "si levanto la cabeza vería hacia el fondo",
                "como las usinas dejaron de eyacular",
                "al cielo, sus vapores.",
                "no más aviones comerciales perforando",
                "nubes negras. no más viento, menos",
                "lluvia, la atmósfera propicia",
                "para la formación de la figura hexagonal",
                "de un copo de nieve tampoco. no más nada.",

        ],
        [
                ">Por un error 404",
                " ",
                ">por un ERROR 404 sos ahora la persona", 
                "más vieja y más joven viva.", 
                "digamos, el único sobreviviente",
                "que queda al ritmo de tu constelación", 
                "espiralada. o esa es la conclusión", 
                "a la que llegás, una vez al mes,", 
                "cuando las colinas que te encapsulan",
                " ",
                "(verdes",
                "colinas mentales",
                "elaboradas con residuos",
                "y sobrantes de tus miedos más frescos)",
                " ",
                "bajás a ver y caminar entre", 
                "y sobre la devastación",
                "esperando dar y recibir", 
                "la misma imagen: algo, alguien", 
                "detrás de la niebla, un desprendimiento",
                "natural como un primo lejano", 
                "que -a la par tuya pero en otro lado-", 
                "también remueve escombros",
                "con un palo de golf y se ríe", 
                "para adentro cada vez que escucha", 
                "y se emociona con el eco de su voz.",

        
        ],
        [
                ">Nunca están dadas las condiciones",
                " ",
                ">porque aunque reniegue y vea el presente",
                "como una transición,",
                "yo también soy uno más.",
                "sigo bronceando mi piel",
                "con luz artificial,",
                "viajo cansado a la altura de los caños",
                "y gente muerta le da nombre",
                "a las calles que camino.",
                "imagino salidas, busco atajos,",
                "me convenzo de lo que pienso.",
                "lo intento,",
                "pero que insoportable",
                "es esta sensación ",
                "de que la fiesta está siempre",
                "en otro lado.",
                "al llegar al fondo del pasillo",
                "solo unos, solo ceros.",
        
        ],
        [
                ">Desconozco las fuentes",
                " ",
                ">pasó de largo la noche, sigo yo",
                "encorvado como una hoz",
                "brillante,",
                "metido en mi capucha negra,",
                "la luz led titila roja,",
                "la lengua del sol ya peina",
                "el paredón vecino,",
                "el sueño que había asomado,",
                "se fue y no volvió,",
                "se hizo un bollo",
                "en la parte trasera",
                "de mi cabeza y desapareció.",
        ],
        [
                ">La curación",
                " ",
                ">no es momento de pensar en las veces", 
                "que pudo -y no lo hizo-", 
                "haber abrazado a un amigo",
                "demasiado tenso por el ruido que le causa",
                "su propia respiración; o contemplado", 
                "la luna llena por más de diez minutos",
                "(ir tras ella, no esperar a que cruce", 
                "la ventana, sino ir recto",
                "hacia su desinteresada luminancia).", 
                "pero ahora el mundo es otro, uno duro", 
                "y sin bordes, voraz como un pitbull", 
                "reventándose la trompa contra el tronco", 
                "de un árbol, muy distinto al que uno", 
                "imaginaba en la suave adolescencia.",
                " ",
                "bajo esa óptica, de lo que tiene", 
                "que encargarse es de no pensar.", 
                "esa es la misión primera. inundar el casco",
                "con frescos pensamientos blancos,",
                "para después sí, trabar la mandíbula,", 
                "cerrar los ojos, concentrarlo todo",
                "en el lengüetazo azul", 
                "que sopla y hace soplar la soldadora *****",
                "* * * **** *** ** *** *** ***** ****** ***",
                "**** *** 250° C ** ** **puestos ** **** **",
                "* ** * en la vena* ***** **de su brazo** *",
                "*** * biónico* ***** * ****** *** *** *",
                "* ***** *** **** * un revestimiento***** *",
                "*** * * ** de chispas** ***** ** plateadas",
                "* **iluminado ***** ** a su antojo *** ****",
                "* *el sótano ** *** *** en el que se oculta.",

        ]

];